### PR TITLE
Port to coqpp.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@ppedrot Is the plan to have all plugins exclusively rely on coqpp for 8.10?

**Comment by ppedrot** [comment]
Indeed.

**Comment by Zimmi48** [comment]
@ppedrot This PR breaks compatibility with Coq 8.9 (not surprising, but let's say the objective of keeping compatibility with two successive versions of Coq won't have lasted long) so this PR should also remove the line testing Coq 8.9 from the `.travis.yml` file.

**Comment by ppedrot** [comment]
@Zimmi48 This should be ready btw.

**Comment by Zimmi48** [comment]
@ppedrot I forgot but since this is removing the dependency on camlp5, can you remove it from the `default.nix` too? I was going to say to do the same to the `opam` file but I realize this file is only present in the v8.8 branch. @fakusb @palmskog: should we copy this file to the v8.9 and master branches as well?

**Comment by ppedrot** [comment]
Unluckily I have no idea about the Nix language, so please go ahead.

**Comment by Zimmi48** [comment]
Done.

**Comment by ppedrot** [comment]
I suspect that this is due to coq_makefile, that still passes the camlp5 library flags to all files it compiles. If we want a transition phase I don't know how to work around this cleanly. Maybe a flag passed to the invocation of coq_makefile?

**Comment by Zimmi48** [comment]
Well, one solution is to continue depending on camlp5 until the Coq packages are migrated to use dune instead of coq_makefile... For the sake of not blocking this PR, I suggest you force-push to this branch to remove my commit.

**Comment by ppedrot** [comment]
Gaah. Done.

**Comment by palmskog** [comment]
@Zimmi48 feel free to copy and adapt the `opam` file to the `v8.9` branch, I was planning to do it myself anyway.

**Comment by Zimmi48** [comment]
So @fakusb, this PR looks ready to me. It is need by @ppedrot to be able to merge a PR upstream.

**Comment by fakusb** [comment]
@Zimmi48 ok, I'm not very knowledgeable in the build infrastructure.
Concerning the opam file: It seems like a good idea, but again I don't have a very deep understanding of opam. If providing properly edited versions of the opam file on the other branches is desired, I can do so tomorrrow.

**Pull request merged**
