### PR TITLE
Move OCaml code out of .ml4 file. 

### PR DESCRIPTION
**Pull request by Zimmi48**
This PR:
- adds a `.gitignore` file;
- renames `Make` into `_CoqProject` which is both more standard and supported by Proof-General and CoqIDE;
- moves OCaml code out of `aac_rewrite.ml4` to a new `.ml` file because merlin doesn't support `.ml4` files.

The goal is to ease the fixing of deprecation warnings using merlin. This in turn should ease the porting to Coq master.

Note that further clean-ups would be probably useful. For instance, `aac_lib.mli` reveals that the `pr_aac_args` function doesn't use its three first arguments. This can probably be rewritten differently...

### CODE REVIEW

**Comment by herbelin** [comment]
@Zimmi48: do I need to wait for the installation of a CI, or can I merge now?

**Comment by Zimmi48** [comment]
@herbelin You are not the maintainer for this repo, @fakusb is ;-)

BTW, I intend to update all coq-community READMEs to put this information, because currently it cannot be found anywhere, except in the corresponding issues on https://github.com/coq-community/manifesto.

But to answer the initial question, I wouldn't wait for CI. I have tested locally on v8.8.

**Comment by herbelin** [comment]
> You are not the maintainer for this repo, @fakusb is ;-)

Oups, sorry.

**Comment by fakusb** [comment]
Thank you very much for the cleanup, as I plan on rewriting and extending most (all?) of the core functionality, I'm not sure that I want to do further clean-ups of the current code base.

**Comment by Zimmi48** [comment]
I see thanks. So I guess that porting to Coq master should not be viewed as a priority.

**Pull request merged**
