### PR TITLE
New lightweight toolbox-based setup.

### PR DESCRIPTION
**Pull request by Zimmi48**
Replacement for #77.

### CODE REVIEW

**Comment by Zimmi48** [comment]
On Travis, the full build without Cache (including Coq) takes 10 to 11 minutes and it takes 12 to 13 minutes on GitHub Actions (+ about 1-2 minutes to upload the artifacts to the coq-community Cachix). Once Coq can be fetched from Cachix, the build takes less than 2 minutes (both on Travis and on GitHub Actions).

**Comment by palmskog** [comment]
The Nix CI job looks good to me, I assume this is usable with `8.14` as `coq_version` also? Is this ready to merge? If so, let me know or just merge it yourself.

After an update to the templates, I think we should try to roll this out to all projects still using Nix CI in coq-community.

**Comment by Zimmi48** [comment]
>The Nix CI job looks good to me, I assume this is usable with `8.14` as `coq_version` also?

With `v8.14` yes (the name of the branch), although there will also be limitations on what Cachix artifacts are available until the adequate Coq PRs are backported. This shouldn't matter as much though, given how infrequently the `v8.14` branch is updated.

With `8.14`, it will work once there is an `8.14` release in nixpkgs.

>Is this ready to merge?

I've finally managed to avoid the rebuild of aac-tactics if the job is restarted (the missing ingredient was to ignore the `.git` folder in the sources). We are now down to a 30s job when nothing has changed.
Now, I just need to force-push to remove the `.travis.yml` configuration, which was there only for testing. Then, this can be considered ready to merge, as long as you don't mind this new CI setup not being fully stable yet.

**Comment by Zimmi48** [comment]
> After an update to the templates, I think we should try to roll this out to all projects still using Nix CI in coq-community.

There are 26 repositories with a `default.nix` file but only 3 with a `nix-action.yml` file (aac-tactics, chapar and huffman) + 1 with a `nix-ci.yml` file (pocklington). For the rest, we should just remove the legacy `default.nix` file.

**Comment by palmskog** [comment]
I'm fine with an experimental setup if it gives CI running times of less than 10 minutes. I will do some testing on some other projects and then merge later tonight.

**Pull request merged**
