### PR TITLE
adapt to #14736

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by palmskog** [comment]
I thought the preferred way to reference natural number operations was to use the `Nat.` qualification, i.e., `Nat.add_assoc`, `Nat.plus`, etc., so wouldn't it be more idiomatic to just do `Import PeanoNat.`?

**Comment by Alizter** [comment]
I can change it to that.

**Comment by palmskog** [comment]
OK, that would be nice, please go ahead. I think it would fit better with how the instances are handled for `Z`.

**Comment by Alizter** [comment]
I've also inlined the #[global]s on the instances to make it easier to maintian. It seems they were find/replaced.

**Comment by palmskog** [comment]
OK, looks good, since it appears backwards-compatible I will merge right away.

**Pull request merged**
