### PR TITLE
[coq] Fix OCaml warnings.

### LINKED ISSUE #32: [warnings] Please fix OCaml warnings
Dear devs,

in Coq we are considering requiring plugins in the CI to use the same set of compiler flags for warnings than the main Coq tree (c.f. https://github.com/coq/coq/pull/9605 ), in particular, this means that the plugins should now compile warning-free, except for deprecation notices.

Note that some of the raised warnings are really fatal, [like missing match cases].

Please, try to fix OCaml warnings present in your codebase, thanks!

### PR DESCRIPTION
**Pull request by ejgallego**
They do seem pretty straightforward, most of them have to do with dead code.

Fixes #32

### CODE REVIEW

**Comment by fakusb** [comment]
Thanks. I need to take a look on the code again, as some of the dead code was used for debugging, so I'm not sure that I want to just remove it.

**Comment by ejgallego** [comment]
Yup, that's a pitfall in ocaml as people tend to leave dead code for debugging due to the runtime cost. However the same warning catches dangerous aliases (as it happens in one case here) so we choose to enable it. Wrapping the debug stuff in a module should work, or having some kind of private namespace

**Comment by Zimmi48** [comment]
All warnings in dead code means that the equation "one warning = one bug" is far to hold here :laughing: 
That being said, it sure would be cleaner to put this debug code somewhere else to make sure that it isn't actually used anywhere else...

**Comment by fakusb** [comment]
Yes, I agree. Will do so.

Théo Zimmermann <notifications@github.com> schrieb am Mi., 20. Feb. 2019 um
14:56 Uhr:

**Comment by Zimmi48** [comment]
OK, I had only seen code removal but it's true that it can sometimes lead to semantics change.

**Comment by ejgallego** [comment]
Thanks! Indeed warnings are far from perfect so I recognize that they can be annoying, up to recently I wasn't worried about CI contribs allowing them but recent set of bugs has shown, IMHO, that this is dangerous.

**Pull request merged**
