### PR TITLE
[coq] Adapt to coq/coq#12372

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by palmskog** [comment]
Oh, I reflexively merged this since there wasn't any indication not to do that. Should I revert?

**Comment by ejgallego** [comment]
> Oh, I reflexively merged this since there wasn't any indication not to do that. Should I revert?

Ops. sorry, we definitively need to improve the workflow here :S Please revert, I will re-submit in draft status.

**Comment by palmskog** [comment]
I've reverted. It would help if the PR text said "don't merge yet".

**Comment by ejgallego** [comment]
Yup, I've update my scripts to do draft PR in this case; sorry again for the incoveniences and thanks for the quick response.

**Pull request merged**
