### PR TITLE
Deploy to Cachix even for PR from forks.

### PR DESCRIPTION
**Pull request by Zimmi48**
Apply the changes from coq-community/templates#100.

### CODE REVIEW

**Review by palmskog — APPROVED** [review]
Looks good to me in the CI logs.

However, I'm always a bit mystified that all Nix builds seem to have this log message multiple times:
```
Error: Cannot find plugins directory
```
It seems harmless and to never affect the build, though.

**Comment by Zimmi48** [comment]
Thanks for reporting, I'll look into it.

**Comment by palmskog** [comment]
If it helps, here's a fresh example from a non-plugin project: https://github.com/coq-community/huffman/pull/30/checks?check_run_id=3508651515#step:8:384

**Comment by Zimmi48** [comment]
OK, the reason was that some version comparison logic mistake made it so that we were using the `COQLIB` variable instead of the `COQMF_COQLIB` variable to tell Coq where to install the library. This is fixed in https://github.com/NixOS/nixpkgs/pull/136908.

**Pull request merged**
