### PR TITLE
Generate CI and documentation from template for v8.9

### PR DESCRIPTION
**Pull request by palmskog**
Use templates for Travis, README, and OPAM.

### CODE REVIEW

**Comment by palmskog** [comment]
@Zimmi48 @vbgl I'm getting some inscrutable Nix CI errors (failed builds) for Coq 8.9:
```shell
$ nix-build --argstr coq-version-or-url "$COQ" --extra-substituters https://coq.cachix.org --trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= coq.cachix.org-1:Jgt0DwGAUo+wpxCM52k2V+E0hLoOzFPzvg94F65agtI="
error: bin_prot-112.24.00 is not available for OCaml 4.06.1
```
For example, the error occurs in [this build](https://travis-ci.com/coq-community/aac-tactics/jobs/162078386). Using latest `.travis.yml` and `default.nix` from the manifesto repo. Any advice?

**Comment by vbgl** [comment]
> error: bin_prot-112.24.00 is not available for OCaml 4.06.1
(use '--show-trace' to show detailed location information)

Please add `--show-trace` to your `nix-build` command, so as to understand where this `bin_prot` comes from.

**Comment by Zimmi48** [comment]
@vbgl I have encountered this error as well but did not have time to debug it yet: one can reproduce it in master with `nix-shell --argstr coq-version-or-url "8.9" --arg shell true` (for instance).

`--show-trace` gives:

```
error: while evaluating the attribute 'buildInputs' of the derivation 'aac-tactics' at /home/theo/dotfiles/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:180:11:
while evaluating 'getOutput' at /home/theo/dotfiles/nixpkgs/lib/attrsets.nix:455:23, called from undefined position:
while evaluating anonymous function at /home/theo/dotfiles/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:128:17, called from undefined position:
while evaluating the attribute 'ocamlPackages' at /home/theo/dotfiles/nixpkgs/lib/attrsets.nix:185:41:
while evaluating 'filterAttrsRecursive' at /home/theo/dotfiles/nixpkgs/lib/attrsets.nix:126:32, called from /home/theo/dotfiles/nixpkgs/lib/attrsets.nix:132:31:
while evaluating anonymous function at /home/theo/dotfiles/nixpkgs/lib/attrsets.nix:128:18, called from /home/theo/dotfiles/nixpkgs/lib/attrsets.nix:128:7:
while evaluating anonymous function at /home/theo/dotfiles/nixpkgs/pkgs/top-level/coq-packages.nix:44:9, called from /home/theo/dotfiles/nixpkgs/lib/attrsets.nix:130:12:
while evaluating the attribute 'bin_prot_p4' at /home/theo/dotfiles/nixpkgs/pkgs/top-level/ocaml-packages.nix:132:5:
while evaluating 'callPackageWith' at /home/theo/dotfiles/nixpkgs/lib/customisation.nix:108:35, called from /home/theo/dotfiles/nixpkgs/pkgs/top-level/ocaml-packages.nix:132:19:
while evaluating 'makeOverridable' at /home/theo/dotfiles/nixpkgs/lib/customisation.nix:67:24, called from /home/theo/dotfiles/nixpkgs/lib/customisation.nix:112:8:
while evaluating anonymous function at /home/theo/dotfiles/nixpkgs/pkgs/development/ocaml-modules/bin_prot/default.nix:1:1, called from /home/theo/dotfiles/nixpkgs/lib/customisation.nix:69:12:
bin_prot-112.24.00 is not available for OCaml 4.06.1
```

**Comment by palmskog** [comment]
@vbgl here is a [build](https://travis-ci.com/coq-community/aac-tactics/jobs/162101267) with `--show-trace` passed to `nix-build`. It's consistent with what @Zimmi48 already showed, as far as I can tell.

**Comment by Zimmi48** [comment]
It should be possible to fix this PR even before NixOS/nixpkgs#51325 is merged and nixpkgs is updated by pinning the source of the packages as I did in coq-community/stalmarck@a925c1fe18626e572f67b20ceefdec9ee567694a.

**Comment by palmskog** [comment]
@Zimmi48 still getting errors even after copying your fix:
```shell
ocamlfind: Package `camlp5.gramlib' not found
make[2]: *** [Makefile.coq:647: src/aac_plugin.cmx] Error 2
make[1]: *** [Makefile.coq:327: all] Error 2
make[1]: Leaving directory '/tmp/nix-build-aac-tactics.drv-0/aac-tactics'
make: *** [Makefile:2: all] Error 2
```
Any further advice?

**Comment by vbgl** [comment]
This means that you need `camlp5` in the `buildInputs`.

**Comment by Zimmi48** [comment]
Indeed. Sorry about that. I did not include it in the template because plugins using Coq master should not use it anymore but for 8.9 and before, this is an additional dependency.

**Pull request merged**
